export default ADD_USER = 'ADD_USER'
export default REMOVE_USER = 'REMOVE_USER'
export default LIST_USERS = 'LIST_USERS'
export default GET_USER = 'GET_USER'
export default DETAIL_USER = 'DETAIL_USER'